# Generated by Django 4.0.6 on 2023-12-20 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Excelfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files')),
            ],
        ),
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30)),
                ('alamat', models.CharField(max_length=200)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-Laki'), ('P', 'Perempuan')], max_length=1)),
                ('status', models.IntegerField(choices=[(1, 'aktif'), (2, 'cuti'), (3, 'studi lanjut'), (4, 'resign'), (5, 'pensiun'), (6, 'meninggal'), (7, 'dikeluarkan')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Hari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_hari', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Jam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_mulai', models.TimeField()),
                ('waktu_selesai', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kelas', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MataPelajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_mapel', models.CharField(max_length=50)),
                ('waktu', models.IntegerField()),
                ('kelas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.kelas')),
            ],
        ),
        migrations.CreateModel(
            name='WaliSiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_hp', models.CharField(max_length=30)),
                ('pendidikan_terakhir', models.IntegerField(choices=[(0, 'Tidak Menempuh Pendidikan'), (1, 'SD'), (2, 'SMP'), (3, 'SMA, D1, D2'), (4, 'D3'), (5, 'S1/D4'), (6, 'S2'), (7, 'S3')], default=3)),
                ('pekerjaan', models.CharField(default='-', max_length=100)),
                ('penghasilan', models.IntegerField(choices=[(1, '0-500.000 rupiah/bulan'), (2, '500.001-1.000.000 rupiah/bulan'), (3, '1.000.001-2.000.000 rupiah/bulan'), (4, '2.000.001-4.500.000 rupiah/bulan'), (5, '4.500.001-6.000.000 rupiah/bulan'), (5, 'lebih dari 6.000.000 rupiah/bulan')], default=3)),
                ('provinsi', models.CharField(default='', max_length=30)),
                ('kota', models.CharField(default='', max_length=30)),
                ('kecamatan', models.CharField(default='', max_length=30)),
                ('kelurahan', models.CharField(default='', max_length=30)),
                ('alamat', models.TextField(default='')),
                ('profile_pic', models.ImageField(blank=True, default='profile.png', null=True, upload_to='')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.guru')),
                ('mapel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.matapelajaran')),
            ],
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nis', models.CharField(blank=True, max_length=20)),
                ('nisn', models.CharField(blank=True, max_length=20)),
                ('tahun_angkatan', models.IntegerField(default=2022)),
                ('nama_siswa', models.CharField(max_length=50)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-Laki'), ('P', 'Perempuan')], max_length=1)),
                ('tempat_lahir', models.CharField(max_length=50)),
                ('tanggal_lahir', models.DateField(null=True)),
                ('is_abk', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(1, 'aktif'), (2, 'keluar/pindah'), (3, 'lulus'), (4, 'meninggal')], default=1)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wali_siswa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siswa', to='core.walisiswa')),
            ],
        ),
        migrations.CreateModel(
            name='Ruangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_ruangan', models.CharField(max_length=50)),
                ('kelas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.kelas')),
            ],
        ),
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_hp', models.CharField(max_length=30)),
                ('pendidikan_terakhir', models.IntegerField(choices=[(0, 'Tidak Menempuh Pendidikan'), (1, 'SD'), (2, 'SMP'), (3, 'SMA, D1, D2'), (4, 'D3'), (5, 'S1/D4'), (6, 'S2'), (7, 'S3')], default=3)),
                ('tempat_lahir', models.CharField(blank=True, max_length=50, null=True)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('provinsi', models.CharField(default='', max_length=30)),
                ('kota', models.CharField(default='', max_length=30)),
                ('kecamatan', models.CharField(default='', max_length=30)),
                ('kelurahan', models.CharField(default='', max_length=30)),
                ('alamat', models.TextField(default='')),
                ('nbm', models.CharField(max_length=30, null=True)),
                ('status', models.IntegerField(choices=[(1, 'aktif'), (2, 'cuti'), (3, 'studi lanjut'), (4, 'resign'), (5, 'pensiun'), (6, 'meninggal'), (7, 'dikeluarkan')], default=1)),
                ('jabatan', models.CharField(max_length=30)),
                ('gol', models.CharField(max_length=10)),
                ('pangkat', models.CharField(max_length=20)),
                ('tmt', models.DateField(null=True)),
                ('profile_pic', models.ImageField(blank=True, default='profile.png', null=True, upload_to='')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tugas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tugas')),
                ('waktu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.hari')),
            ],
        ),
        migrations.AddField(
            model_name='hari',
            name='jam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.jam'),
        ),
    ]
